import './globals.css'
import { Poppins } from 'next/font/google'
import { AuthProvider } from '../context/AuthContext'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
})

export const metadata = {
  title: 'Hazaribagh Leather',
  description: 'Bangladesh leather shop demo',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <AuthProvider>
          <Navbar />
          <main className="min-h-[80vh] bg-[#f7f8fa] text-neutral-900">
            {children}
          </main>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  )
}



// import './globals.css'
// import { Inter } from 'next/font/google'
// import { AuthProvider } from '../context/AuthContext'
// import Navbar from '../components/Navbar'
// import Footer from '../components/Footer'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Hazaribagh Leather',
//   description: 'Bangladesh leather shop demo',
// }

// export default function RootLayout({ children }: { children: React.ReactNode }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <AuthProvider>
//           <Navbar />
//           <main className="min-h-[80vh]">{children}</main>
//           <Footer />
//         </AuthProvider>
//       </body>
//     </html>
//   )
// }


// import './globals.css'
// import { Inter } from 'next/font/google'
// import { AuthProvider } from '../context/AuthContext'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Hazaribagh Leather Demo',
//   description: 'E-commerce demo for sellers',
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <AuthProvider>
//           {children}
//         </AuthProvider>
//       </body>
//     </html>
//   )
// }


// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
